# Generated by Django 4.2 on 2023-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('principal_role', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('birth_place', models.CharField(max_length=150)),
                ('biography', models.TextField()),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=10)),
                ('original_language', models.CharField(max_length=10)),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Presupuesto')),
                ('income', models.IntegerField(blank=True, null=True, verbose_name='Ingresos')),
                ('year', models.DateField()),
                ('image', models.URLField()),
                ('duration', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=5)),
                ('description', models.CharField()),
                ('cast', models.ManyToManyField(related_name='rel_cast', to='core.person')),
                ('category', models.ManyToManyField(related_name='rel_category', to='core.category')),
                ('characters', models.ManyToManyField(related_name='rel_characters', to='core.person')),
                ('director', models.ManyToManyField(related_name='rel_director', to='core.person')),
                ('novel', models.ManyToManyField(related_name='rel_novel', to='core.person')),
                ('screenplay', models.ManyToManyField(related_name='rel_screenplay', to='core.person')),
                ('story', models.ManyToManyField(related_name='rel_story', to='core.person')),
                ('writer', models.ManyToManyField(related_name='rel_writer', to='core.person')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
                'ordering': ['pk'],
            },
        ),
    ]
