# Generated by Django 4.1.1 on 2023-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
