# Generated by Django 4.1.1 on 2023-04-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_film_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='certification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
