# Generated by Django 4.1.1 on 2023-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_person_age_alter_person_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='film',
            name='income',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ingresos'),
        ),
    ]
