# Generated by Django 4.1.1 on 2023-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_film_budget_alter_film_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.CharField(max_length=50),
        ),
    ]
