# Generated by Django 4.1.1 on 2023-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_film_original_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
